### ISSUE TITLE
design an abstraction for single request handler

### ISSUE THREAD

**Issue by lehecka** [rsocket/rsocket-cpp#173]
For scenarios when you want to implement ReactiveSocket proxy, it would be more efficient to work with API which would not allocate object for each stream, including all the overhead of smart pointers, etc.
The idea is to have an interface for having one request handler instance per reactive socket instance. All the current convenience classes like Subscriptions, Subscribers, etc. would be built atop this interface.

**Comment by yschimke** [comment]
Why one handler instance per reactivesocket?  why not just make the reactivesocket id part of the params to each callback method?

**Comment by jspahrsummers** [comment]
@yschimke That would require some kind of global state (and therefore potentially synchronization), whereas hanging off of the socket only requires per-instance state.

**Comment by yschimke** [comment]
@jspahrsummers we split off by eventbase immediately after accepting a connection (eb + DuplexConnection => ReactiveSocket), so I was suggesting a callback per eventbase.

**Comment by benjchristensen** [comment]
Is this something we still intend on pursuing further? The new APIs already do support a global `Responder` instance being used for every request. We do however still allocate a state machine per stream.

**Comment by alexmalyshev** [comment]
Stale.  Let's open a fresh task referring to the new API if we feel this is worth doing.
