### ISSUE TITLE
FrameBufferAllocator should be passed to ReactiveSocket in the constructor

### ISSUE THREAD

**Issue by lehecka** [rsocket/rsocket-cpp#196]
The allocator allocates extra bytes for frame size. It is needed for framing. But with different transport layer (different DuplexConnection) we don't need the extra bytes so we can use a different FrameBufferAllocator.

currently the allocator is a static singleton.
it would be good to pass it in the constructor

see discussion in https://github.com/ReactiveSocket/reactivesocket-cpp/pull/194

**Comment by benjchristensen** [comment]
Is this still applicable?

**Comment by alexmalyshev** [comment]
Not applicable.
