### ISSUE TITLE
onDisconnected() not called on close()

### ISSUE THREAD

**Issue by martinsix** [rsocket/rsocket-cpp#269]
Currently, ReactiveSocket::close() does not call onDisconnected() (if we are currently connected), but I think it should. Is there a reason why this is not done right now?

**Comment by yschimke** [comment]
A similar question: what does disconnecting a non resumable client RS mean?  should it actually mean disconnect, then close?

**Comment by benjchristensen** [comment]
This code no longer exists, but in the new code are we now calling the correct callbacks?

**Comment by alexmalyshev** [comment]
We're calling `onDisconnected()` for resumable connections, and `onClosed()` for non-resumable ones.
