### ISSUE TITLE
stream level errors should not bring the the whole socket down

### ISSUE THREAD

**Issue by lehecka** [rsocket/rsocket-cpp#311]
Stream level errors should bring one stream down, not the whole socket.

**Comment by benjchristensen** [comment]
Is this fixed yet? We should have a unit test proving this :-)

**Comment by alexmalyshev** [comment]
This /shouldn't/ be the case, as stream errors call back up to `RSocketStateMachine::endStream()`, which doesn't close the whole socket.

If we have specific places where this is happening then we can open an issue for those.
