### ISSUE TITLE
Library Size

### ISSUE THREAD

**Issue by benjchristensen** [rsocket/rsocket-cpp#32]
The current compiled size of `libReactiveSocket.a` is 1.6M:

```
1.6M May 17 10:12 libReactiveSocket.a
```

The Java version is 185k and is feature complete:

```
185K May 17 10:14 reactivesocket-0.1.1-SNAPSHOT.jar
```

Java currently has a dependency on a 200k library, but that can likely be reduced with some effort. 

So, reactivesocket-cpp is still not complete, and we are at 1.6M vs the complete Java impl being < 400k. 

Folly is > 50M for everything, so I'm assuming the static linking is just pulling from it what is needed (showing my lack of C++ experience):

```
-rwxr-xr-x  1 root  wheel   5.9M Jan 11 02:15 /usr/local/lib/libfolly.57.dylib
-rw-r--r--  1 root  wheel    68M Jan 11 02:15 /usr/local/lib/libfolly.a
```

Is this greater size expected for C++? Or is it something we can reduce by being more careful with our dependencies?

I am exploring this due to desire to use this on mobile.

**Comment by stupaq-fb** [comment]
Optimising for code size gives ~800kB. We probably only need IOBuf from folly, which we can strip/reimplement easily. Also, there are plenty of symbols that we don't need to export (mangled strings stored in object files). There is tremendous amount of room for improvements at this stage, even without touching actual code, I think.

**Comment by lehecka** [comment]
did we enable linker to exclude unused symbols like unused global variables?

**Comment by stupaq-fb** [comment]
Which flag exactly?

I'm just going to leave it here for anyone who ends up working on, this https://blog.algolia.com/android-ndk-how-to-reduce-libs-size/.

**Comment by lehecka** [comment]
we are down to 250k
We can remove the rest of template code with some refactoring and get to even smaller size.

**Comment by benjchristensen** [comment]
Excellent news, thank you Ondrej for the update and work to get to this point.

**Comment by yschimke** [comment]
Can we close this now?
