### ISSUE TITLE
Server ReactiveSocket should not have any notion of current or default protocol version for servers

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-cpp#496]
This is a dangerous default, as it special cases the latest  <-> latest mode in clients and servers.

But we need an equal amount of testing of older versions to account for deployed clients that connect to upgraded servers etc.

Both constructors of FramedDuplexConnection are problematic, ideally this should just always be unknown, unless we define that a particular version means assert and fail if its not this version.

https://github.com/rsocket/rsocket-cpp/blob/637efb1821ba75276e8e75a376f1976a7be9ce2d/src/framing/FramedDuplexConnection.cpp#L15

**Comment by alexmalyshev** [comment]
I /believe/ this is fixed.  We default to `ProtocolVersion::Unknown` to the `FramedFoo` constructs, and then autodetect the version based on the first frame we receive.
