### ISSUE TITLE
Switch yarpl from std::exception_ptr to folly::exception_wrapper 

### ISSUE THREAD

**Issue by Cristinag** [rsocket/rsocket-cpp#589]
In the LiveServer code we're using folly::exception_wrapper extensively, which means that we will have the need to transform from std::exception_ptr to folly::exception_wrapper which is hacky (see D5442765) and expensive (as we need to rethrow exceptions).

Can instead use folly::exception_wrapper in rsocket?

**Comment by lexs** [comment]
This comes up a bunch of times inside the rsocket codebase too where we have to rethrow the exception just to get the exception message.

**Comment by lehecka** [comment]
Lets leave this decision to AlexM who will lead the performance improvements and benchmarking project.
In general I agree it feels wasteful to switch back and forth. However yarpl lib dirsnt depend on folly.

**Comment by lexs** [comment]
@alexmalyshev How do you feel about this? Care if we switch?

**Comment by alexmalyshev** [comment]
I don't care about having a dependency on folly.  In my mind, I never really saw yarpl as being separate from rsocket (no one is leading the charge to make it an awesome standalone library), and rsocket will most definitely depend on folly going forward.

I'm a tentative supporter of switching to `folly::exception_wrapper`.

**Comment by phoad** [comment]
https://github.com/rsocket/rsocket-cpp/pull/662
I have updated the Github project accordingly. Next we need to update the dependent projects.
