### ISSUE TITLE
Unable to checkout on Windows

### ISSUE THREAD

**Issue by michaelaeriksen** [rsocket/rsocket-cpp#680]
Please remove these files or rename them.

error: unable to create file test/fuzzer_testcases/frame_fuzzer/id:000000,sig:11,src:000000,op:havoc,rep:2: Invalid argument
error: unable to create file test/fuzzer_testcases/frame_fuzzer/id:000001,sig:11,src:000000,op:havoc,rep:16: Invalid argument

**Comment by alexmalyshev** [comment]
@dymk Can we rename these?

**Comment by dymk** [comment]
lolntfs

Yep we can change these file names.

Slightly related point, I don't think we support building on Windows (because of the Folly dependency)? 
Regardless, there's still value in at least being able to checkout/cross compile on Windows.
