### ISSUE TITLE
yarpl::enable_get_ref causes build break

### ISSUE THREAD

**Issue by phoad** [rsocket/rsocket-cpp#780]
Build issues:

yarpl/include/yarpl/Refcounted.h:385:7: error: 'yarpl::enable_get_ref' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]
class enable_get_ref {
      ^
yarpl/include/yarpl/Refcounted.h:385:7: error: 'yarpl::enable_get_ref' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]
class enable_get_ref {

**Comment by dymk** [comment]
Hmmmm. Looks like in debug mode it needs `virtual ~enable_get_ref() {}`?

What build config causes this error?
