### ISSUE TITLE
test_utils/utils.h is removed but still included in CMakeLists.txt

### ISSUE THREAD

**Issue by ziruiliu** [rsocket/rsocket-cpp#864]
In the latest change (rev D7798385), file yarpl/test_utils/utils.h is completed removed.
However in CMakeLists.txt the file is still included in line 135.
This will cause build failed

**Comment by ManasviniGanesh** [comment]
@ziruiliu    I am facing the same thing. I NEED to use this library as it is a dependency. Did you find some workaround ?

**Comment by lexs** [comment]
I just started import of https://github.com/rsocket/rsocket-cpp/pull/865. Let me know if that doesn't fix your problems. Note that Travis is still failing due to gtest not supporting move-only types which I don't have time to fix right now.

**Comment by phoad** [comment]
I will prioritize landing that diff and update this thread.

**Comment by phoad** [comment]
Fixed :)
